name: Master

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'
    paths:
      - 'src/**'

jobs:
  unit-tests:
    name: Unit tests
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout branch
        uses: actions/checkout@main

      - name: Build and run unit tests
        run: ./utils/unit.test.sh
